# Generated by Django 6.0.7 on 2026-07-13 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='店铺名')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL标识')),
                ('category', models.CharField(choices=[('肉类', '肉类'), ('海鲜', '海鲜'), ('素食', '素食'), ('甜点', '甜点')], max_length=10, verbose_name='分类')),
                ('description', models.TextField(verbose_name='描述')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='地址')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='纬度')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='经度')),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=2, verbose_name='评分')),
                ('opening_hours', models.CharField(default='17:00-02:00', max_length=50, verbose_name='营业时间')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='电话')),
                ('image_url', models.URLField(blank=True, max_length=500, verbose_name='封面图片')),
                ('popularity', models.IntegerField(default=0, verbose_name='人气')),
                ('waiting', models.CharField(default='约5分钟', max_length=20, verbose_name='排队时间')),
                ('spicy', models.BooleanField(default=False, verbose_name='辣味')),
                ('vegetarian', models.BooleanField(default=False, verbose_name='素食')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '店铺',
                'verbose_name_plural': '店铺',
                'ordering': ['-popularity'],
            },
        ),
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='姓名')),
                ('role', models.CharField(default='老板', max_length=30, verbose_name='职位')),
                ('avatar_url', models.URLField(blank=True, max_length=500, verbose_name='头像')),
                ('bio', models.TextField(blank=True, verbose_name='简介')),
                ('is_primary', models.BooleanField(default=False, verbose_name='主要联系人')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='market.store', verbose_name='所属店铺')),
            ],
            options={
                'verbose_name': '经营人员',
                'verbose_name_plural': '经营人员',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=30, verbose_name='昵称')),
                ('avatar', models.CharField(blank=True, max_length=100, verbose_name='头像标识')),
                ('rating', models.SmallIntegerField(verbose_name='评分(1-5)')),
                ('food', models.CharField(blank=True, max_length=50, verbose_name='所点美食')),
                ('comment', models.TextField(verbose_name='评价内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='评价时间')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='market.store', verbose_name='所属店铺')),
            ],
            options={
                'verbose_name': '食客评价',
                'verbose_name_plural': '食客评价',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='商品名')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('price', models.CharField(default='¥10/份', max_length=30, verbose_name='价格')),
                ('special_price', models.CharField(blank=True, max_length=30, verbose_name='优惠价')),
                ('image_url', models.URLField(blank=True, max_length=500, verbose_name='图片')),
                ('is_recommended', models.BooleanField(default=False, verbose_name='招牌推荐')),
                ('spicy_level', models.SmallIntegerField(default=0, verbose_name='辣度(0-3)')),
                ('is_vegetarian', models.BooleanField(default=False, verbose_name='素食')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='market.store', verbose_name='所属店铺')),
            ],
            options={
                'verbose_name': '售卖商品',
                'verbose_name_plural': '售卖商品',
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='证书名称')),
                ('issuer', models.CharField(max_length=100, verbose_name='颁发机构')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='颁发日期')),
                ('image_url', models.URLField(blank=True, max_length=500, verbose_name='证书图片')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='market.store', verbose_name='所属店铺')),
            ],
            options={
                'verbose_name': '经营证书',
                'verbose_name_plural': '经营证书',
            },
        ),
    ]
