# Generated by Django 6.0.7 on 2026-07-14 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名/品牌')),
                ('phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('application_type', models.CharField(choices=[('摊位入驻', '摊位入驻'), ('求职应聘', '求职应聘'), ('商务合作', '商务合作'), ('其他咨询', '其他咨询')], default='摊位入驻', max_length=10, verbose_name='申请类型')),
                ('message', models.TextField(blank=True, verbose_name='留言')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('contacted', '已联系'), ('closed', '已关闭')], default='pending', max_length=10, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
            ],
            options={
                'verbose_name': '入驻/求职申请',
                'verbose_name_plural': '入驻/求职申请',
                'ordering': ['-created_at'],
            },
        ),
    ]
