# Generated by Django 6.0.7 on 2026-07-14 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_merchantprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='活动标题')),
                ('date', models.CharField(max_length=50, verbose_name='活动日期')),
                ('description', models.TextField(verbose_name='活动描述')),
                ('tag', models.CharField(blank=True, choices=[('热门', '热门'), ('音乐', '音乐'), ('福利', '福利'), ('限定', '限定')], max_length=10, verbose_name='标签')),
                ('image_url', models.URLField(blank=True, max_length=500, verbose_name='图片')),
                ('is_past', models.BooleanField(default=False, verbose_name='往期活动')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '活动公告',
                'verbose_name_plural': '活动公告',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TodaySpecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='特价名称')),
                ('description', models.TextField(verbose_name='描述')),
                ('price', models.CharField(default='¥28', max_length=30, verbose_name='价格')),
                ('image_url', models.URLField(blank=True, max_length=500, verbose_name='图片')),
                ('tag', models.CharField(default='主厨特选', max_length=20, verbose_name='标签')),
                ('is_active', models.BooleanField(default=True, verbose_name='当前生效')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specials', to='market.store', verbose_name='所属店铺')),
            ],
            options={
                'verbose_name': '今日特价',
                'verbose_name_plural': '今日特价',
                'ordering': ['-created_at'],
            },
        ),
    ]
