# Generated by Django 6.0.7 on 2026-07-14 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_event_todayspecial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('pending', '待审批'), ('approved', '已审批'), ('published', '已发布'), ('archived', '已下架')], default='pending', max_length=10, verbose_name='状态'),
        ),
    ]
